// Code generated by swaggo/swag. DO NOT EDIT.

package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/identity/create": {
            "post": {
                "description": "Create Identity an User",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Identity"
                ],
                "summary": "Create Identity",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Onboarding Reference",
                        "name": "X-Onboarding-Reference",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "User Reference",
                        "name": "X-User-Reference",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Phone",
                        "name": "X-Phone",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "IMEI",
                        "name": "X-Imei",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Device Type",
                        "name": "X-Device-Type",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Device Brand",
                        "name": "X-Device-Brand",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Device Model",
                        "name": "X-Device-Model",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Device Reference",
                        "name": "X-Device-Reference",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "User request body",
                        "name": "requestBody",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.IdentityDTO"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Success",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/helper.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/identity/device": {
            "post": {
                "description": "Get Identity by Device",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Identity"
                ],
                "summary": "Get Identity by Device",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Onboarding Reference",
                        "name": "X-Onboarding-Reference",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "User Reference",
                        "name": "X-User-Reference",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Phone",
                        "name": "X-Phone",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "IMEI",
                        "name": "X-Imei",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Device Type",
                        "name": "X-Device-Type",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Device Brand",
                        "name": "X-Device-Brand",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Device Model",
                        "name": "X-Device-Model",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Device Reference",
                        "name": "X-Device-Reference",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "User request body",
                        "name": "requestBody",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.DeviceDto"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Success",
                        "schema": {
                            "$ref": "#/definitions/entity.Identity"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/helper.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/identity/{user_reference}": {
            "get": {
                "description": "Get Identity by user reference",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Identity"
                ],
                "summary": "Get Identity by user reference",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User reference",
                        "name": "user_reference",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Success",
                        "schema": {
                            "$ref": "#/definitions/entity.Identity"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/helper.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/identity/{user_reference}/create-password": {
            "post": {
                "description": "Create Password",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Identity"
                ],
                "summary": "Create Password",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Onboarding Reference",
                        "name": "X-Onboarding-Reference",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "User Reference",
                        "name": "X-User-Reference",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Phone",
                        "name": "X-Phone",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "IMEI",
                        "name": "X-Imei",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Device Type",
                        "name": "X-Device-Type",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Device Brand",
                        "name": "X-Device-Brand",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Device Model",
                        "name": "X-Device-Model",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Device Reference",
                        "name": "X-Device-Reference",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "User reference",
                        "name": "user_reference",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "User request body",
                        "name": "requestBody",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.CreatePasswordDTO"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Success",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/helper.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/identity/{user_reference}/create-pin": {
            "post": {
                "description": "Create Pin",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Identity"
                ],
                "summary": "Create Pin",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Onboarding Reference",
                        "name": "X-Onboarding-Reference",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "User Reference",
                        "name": "X-User-Reference",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Phone",
                        "name": "X-Phone",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "IMEI",
                        "name": "X-Imei",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Device Type",
                        "name": "X-Device-Type",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Device Brand",
                        "name": "X-Device-Brand",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Device Model",
                        "name": "X-Device-Model",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Device Reference",
                        "name": "X-Device-Reference",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "User reference",
                        "name": "user_reference",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "User request body",
                        "name": "requestBody",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.CreatePinDTO"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Success",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/helper.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/identity/{user_reference}/disable": {
            "put": {
                "description": "Disable Identity",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Identity"
                ],
                "summary": "Disable Identity",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Onboarding Reference",
                        "name": "X-Onboarding-Reference",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "User Reference",
                        "name": "X-User-Reference",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Phone",
                        "name": "X-Phone",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "IMEI",
                        "name": "X-Imei",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Device Type",
                        "name": "X-Device-Type",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Device Brand",
                        "name": "X-Device-Brand",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Device Model",
                        "name": "X-Device-Model",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Device Reference",
                        "name": "X-Device-Reference",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "User reference",
                        "name": "user_reference",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Success",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/helper.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/identity/{user_reference}/enable": {
            "put": {
                "description": "Enable Identity",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Identity"
                ],
                "summary": "Enable Identity",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Onboarding Reference",
                        "name": "X-Onboarding-Reference",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "User Reference",
                        "name": "X-User-Reference",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Phone",
                        "name": "X-Phone",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "IMEI",
                        "name": "X-Imei",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Device Type",
                        "name": "X-Device-Type",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Device Brand",
                        "name": "X-Device-Brand",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Device Model",
                        "name": "X-Device-Model",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Device Reference",
                        "name": "X-Device-Reference",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "User reference",
                        "name": "user_reference",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Success",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/helper.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/login/password": {
            "post": {
                "description": "Login With Password",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Identity"
                ],
                "summary": "Login With Password",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Onboarding Reference",
                        "name": "X-Onboarding-Reference",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "User Reference",
                        "name": "X-User-Reference",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Phone",
                        "name": "X-Phone",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "IMEI",
                        "name": "X-Imei",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Device Type",
                        "name": "X-Device-Type",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Device Brand",
                        "name": "X-Device-Brand",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Device Model",
                        "name": "X-Device-Model",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Device Reference",
                        "name": "X-Device-Reference",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "User reference",
                        "name": "user_reference",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "User request body",
                        "name": "requestBody",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.AuthenticatePasswordDTO"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Success",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/helper.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/login/pin": {
            "post": {
                "description": "Login With Pin",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Identity"
                ],
                "summary": "Login With Pin",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Onboarding Reference",
                        "name": "X-Onboarding-Reference",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "User Reference",
                        "name": "X-User-Reference",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Phone",
                        "name": "X-Phone",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "IMEI",
                        "name": "X-Imei",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Device Type",
                        "name": "X-Device-Type",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Device Brand",
                        "name": "X-Device-Brand",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Device Model",
                        "name": "X-Device-Model",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Device Reference",
                        "name": "X-Device-Reference",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "User reference",
                        "name": "user_reference",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "User request body",
                        "name": "requestBody",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.AuthenticatePinDTO"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Success",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/helper.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/logout/{user_reference}": {
            "post": {
                "description": "Logout User",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Identity"
                ],
                "summary": "Logout",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Onboarding Reference",
                        "name": "X-Onboarding-Reference",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "User Reference",
                        "name": "X-User-Reference",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Phone",
                        "name": "X-Phone",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "IMEI",
                        "name": "X-Imei",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Device Type",
                        "name": "X-Device-Type",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Device Brand",
                        "name": "X-Device-Brand",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Device Model",
                        "name": "X-Device-Model",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Device Reference",
                        "name": "X-Device-Reference",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "User reference",
                        "name": "user_reference",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "User request body",
                        "name": "requestBody",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.RevokeAccessTokenDTO"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "User has been logged out",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/helper.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/otp/{user_reference}/validate": {
            "post": {
                "description": "Validate OTP",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Identity"
                ],
                "summary": "Validate OTP",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Onboarding Reference",
                        "name": "X-Onboarding-Reference",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "User Reference",
                        "name": "X-User-Reference",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Phone",
                        "name": "X-Phone",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "IMEI",
                        "name": "X-Imei",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Device Type",
                        "name": "X-Device-Type",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Device Brand",
                        "name": "X-Device-Brand",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Device Model",
                        "name": "X-Device-Model",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Device Reference",
                        "name": "X-Device-Reference",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "User reference",
                        "name": "user_reference",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "User request body",
                        "name": "requestBody",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.ValidateOtp"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OTP sent for validation",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/helper.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/password/{user_reference}/change": {
            "put": {
                "description": "Change User Password",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Identity"
                ],
                "summary": "Change Password",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Onboarding Reference",
                        "name": "X-Onboarding-Reference",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "User Reference",
                        "name": "X-User-Reference",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Phone",
                        "name": "X-Phone",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "IMEI",
                        "name": "X-Imei",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Device Type",
                        "name": "X-Device-Type",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Device Brand",
                        "name": "X-Device-Brand",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Device Model",
                        "name": "X-Device-Model",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Device Reference",
                        "name": "X-Device-Reference",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "User reference",
                        "name": "user_reference",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "User request body",
                        "name": "requestBody",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.ChangePasswordDTO"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Success",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/helper.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/password/{user_reference}/recovery/complete": {
            "put": {
                "description": "Complete Password Recovery",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Identity"
                ],
                "summary": "Complete Password Recovery",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Onboarding Reference",
                        "name": "X-Onboarding-Reference",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "User Reference",
                        "name": "X-User-Reference",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Phone",
                        "name": "X-Phone",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "IMEI",
                        "name": "X-Imei",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Device Type",
                        "name": "X-Device-Type",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Device Brand",
                        "name": "X-Device-Brand",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Device Model",
                        "name": "X-Device-Model",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Device Reference",
                        "name": "X-Device-Reference",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "User reference",
                        "name": "user_reference",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "User request body",
                        "name": "requestBody",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.CompletePasswordRecoveryDTO"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Success",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/helper.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/password/{user_reference}/recovery/start": {
            "post": {
                "description": "Start Passsword Recovery",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Identity"
                ],
                "summary": "Start Passsword Recovery",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Onboarding Reference",
                        "name": "X-Onboarding-Reference",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "User Reference",
                        "name": "X-User-Reference",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Phone",
                        "name": "X-Phone",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "IMEI",
                        "name": "X-Imei",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Device Type",
                        "name": "X-Device-Type",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Device Brand",
                        "name": "X-Device-Brand",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Device Model",
                        "name": "X-Device-Model",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Device Reference",
                        "name": "X-Device-Reference",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "User reference",
                        "name": "user_reference",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OTP request has been sent. Please wait for OTP",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/helper.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/password/{user_reference}/reset": {
            "put": {
                "description": "Reset User Password",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Identity"
                ],
                "summary": "Reset Password",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Onboarding Reference",
                        "name": "X-Onboarding-Reference",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "User Reference",
                        "name": "X-User-Reference",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Phone",
                        "name": "X-Phone",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "IMEI",
                        "name": "X-Imei",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Device Type",
                        "name": "X-Device-Type",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Device Brand",
                        "name": "X-Device-Brand",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Device Model",
                        "name": "X-Device-Model",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Device Reference",
                        "name": "X-Device-Reference",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "User reference",
                        "name": "user_reference",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "User request body",
                        "name": "requestBody",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.ResetPasswordDTO"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Success",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/helper.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/pin/{user_reference}/change": {
            "put": {
                "description": "Change Pin",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Identity"
                ],
                "summary": "Change Pin",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Onboarding Reference",
                        "name": "X-Onboarding-Reference",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "User Reference",
                        "name": "X-User-Reference",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Phone",
                        "name": "X-Phone",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "IMEI",
                        "name": "X-Imei",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Device Type",
                        "name": "X-Device-Type",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Device Brand",
                        "name": "X-Device-Brand",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Device Model",
                        "name": "X-Device-Model",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Device Reference",
                        "name": "X-Device-Reference",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "User reference",
                        "name": "user_reference",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "User request body",
                        "name": "requestBody",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.ChangePinDTO"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Success",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/helper.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/pin/{user_reference}/recovery/complete": {
            "put": {
                "description": "Complete Pin Recovery",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Identity"
                ],
                "summary": "Complete Pin Recovery",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Onboarding Reference",
                        "name": "X-Onboarding-Reference",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "User Reference",
                        "name": "X-User-Reference",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Phone",
                        "name": "X-Phone",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "IMEI",
                        "name": "X-Imei",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Device Type",
                        "name": "X-Device-Type",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Device Brand",
                        "name": "X-Device-Brand",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Device Model",
                        "name": "X-Device-Model",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Device Reference",
                        "name": "X-Device-Reference",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "User reference",
                        "name": "user_reference",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "User request body",
                        "name": "requestBody",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.CompletePinRecoveryDTO"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Success",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/helper.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/pin/{user_reference}/recovery/start": {
            "post": {
                "description": "Start Pin Recovery",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Identity"
                ],
                "summary": "Start Pin Recovery",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Onboarding Reference",
                        "name": "X-Onboarding-Reference",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "User Reference",
                        "name": "X-User-Reference",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Phone",
                        "name": "X-Phone",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "IMEI",
                        "name": "X-Imei",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Device Type",
                        "name": "X-Device-Type",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Device Brand",
                        "name": "X-Device-Brand",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Device Model",
                        "name": "X-Device-Model",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Device Reference",
                        "name": "X-Device-Reference",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "User reference",
                        "name": "user_reference",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OTP request has been sent. Please wait for OTP",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/helper.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/pin/{user_reference}/reset": {
            "put": {
                "description": "Reset Pin",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Identity"
                ],
                "summary": "Reset Pin",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Onboarding Reference",
                        "name": "X-Onboarding-Reference",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "User Reference",
                        "name": "X-User-Reference",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Phone",
                        "name": "X-Phone",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "IMEI",
                        "name": "X-Imei",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Device Type",
                        "name": "X-Device-Type",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Device Brand",
                        "name": "X-Device-Brand",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Device Model",
                        "name": "X-Device-Model",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Device Reference",
                        "name": "X-Device-Reference",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "User reference",
                        "name": "user_reference",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "User request body",
                        "name": "requestBody",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.ResetPinDTO"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Success",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/helper.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/token/{user_reference}/verify": {
            "post": {
                "description": "Verify Access Token",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Identity"
                ],
                "summary": "Verify Access Token",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Onboarding Reference",
                        "name": "X-Onboarding-Reference",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "User Reference",
                        "name": "X-User-Reference",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Phone",
                        "name": "X-Phone",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "IMEI",
                        "name": "X-Imei",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Device Type",
                        "name": "X-Device-Type",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Device Brand",
                        "name": "X-Device-Brand",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Device Model",
                        "name": "X-Device-Model",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Device Reference",
                        "name": "X-Device-Reference",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "User reference",
                        "name": "user_reference",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "User request body",
                        "name": "requestBody",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.VerifyAccessTokenDTO"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Success",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/helper.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "dto.AuthenticatePasswordDTO": {
            "type": "object",
            "required": [
                "password",
                "user_reference"
            ],
            "properties": {
                "password": {
                    "description": "Must be alphanumeric and length between 8 and 30",
                    "type": "string"
                },
                "user_reference": {
                    "description": "Must be a valid UUID v4 string",
                    "type": "string"
                }
            }
        },
        "dto.AuthenticatePinDTO": {
            "type": "object",
            "required": [
                "pin",
                "user_reference"
            ],
            "properties": {
                "pin": {
                    "description": "Must be numeric and exactly 6 characters long",
                    "type": "string"
                },
                "user_reference": {
                    "description": "Must be a valid UUID v4 string",
                    "type": "string"
                }
            }
        },
        "dto.ChangePasswordDTO": {
            "type": "object",
            "required": [
                "new_password",
                "old_password"
            ],
            "properties": {
                "new_password": {
                    "description": "Must be alphanumeric and length between 8 and 30",
                    "type": "string"
                },
                "old_password": {
                    "description": "Must be alphanumeric and length between 8 and 30",
                    "type": "string"
                }
            }
        },
        "dto.ChangePinDTO": {
            "type": "object",
            "required": [
                "new_pin",
                "old_pin"
            ],
            "properties": {
                "new_pin": {
                    "description": "Must be numeric and exactly 4 characters long",
                    "type": "string"
                },
                "old_pin": {
                    "description": "Must be numeric and exactly 4 characters long",
                    "type": "string"
                }
            }
        },
        "dto.CompletePasswordRecoveryDTO": {
            "type": "object",
            "required": [
                "new_password"
            ],
            "properties": {
                "new_password": {
                    "description": "Must be alphanumeric and length between 8 and 30",
                    "type": "string"
                }
            }
        },
        "dto.CompletePinRecoveryDTO": {
            "type": "object",
            "required": [
                "new_pin",
                "otp"
            ],
            "properties": {
                "new_pin": {
                    "description": "Must be numeric and exactly 4 characters long",
                    "type": "string"
                },
                "otp": {
                    "description": "Must be numeric and exactly 6 digits long",
                    "type": "string"
                }
            }
        },
        "dto.CreatePasswordDTO": {
            "type": "object",
            "required": [
                "password"
            ],
            "properties": {
                "password": {
                    "description": "Must be alphanumeric and length between 8 and 30",
                    "type": "string"
                }
            }
        },
        "dto.CreatePinDTO": {
            "type": "object",
            "required": [
                "pin"
            ],
            "properties": {
                "pin": {
                    "description": "Must be numeric and exactly 4 characters long",
                    "type": "string"
                }
            }
        },
        "dto.DeviceDto": {
            "type": "object",
            "required": [
                "brand",
                "imei",
                "model"
            ],
            "properties": {
                "brand": {
                    "type": "string"
                },
                "device_reference": {
                    "type": "string"
                },
                "imei": {
                    "type": "string"
                },
                "model": {
                    "type": "string"
                },
                "type": {
                    "$ref": "#/definitions/shared.DeviceType"
                }
            }
        },
        "dto.IdentityDTO": {
            "type": "object",
            "required": [
                "device",
                "phone",
                "user_reference"
            ],
            "properties": {
                "device": {
                    "$ref": "#/definitions/dto.DeviceDto"
                },
                "phone": {
                    "description": "Must be a valid E.164 format phone number",
                    "type": "string"
                },
                "user_reference": {
                    "description": "Must be a valid UUID v4 string",
                    "type": "string"
                }
            }
        },
        "dto.ResetPasswordDTO": {
            "type": "object",
            "required": [
                "new_password"
            ],
            "properties": {
                "new_password": {
                    "description": "Must be alphanumeric and length between 8 and 30",
                    "type": "string"
                }
            }
        },
        "dto.ResetPinDTO": {
            "type": "object",
            "required": [
                "new_pin"
            ],
            "properties": {
                "new_pin": {
                    "description": "Must be numeric and exactly 4 characters long",
                    "type": "string"
                }
            }
        },
        "dto.RevokeAccessTokenDTO": {
            "type": "object",
            "required": [
                "access_token"
            ],
            "properties": {
                "access_token": {
                    "description": "Access token should not be empty",
                    "type": "string"
                }
            }
        },
        "dto.ValidateOtp": {
            "type": "object",
            "required": [
                "contact",
                "device",
                "otp",
                "user_reference"
            ],
            "properties": {
                "contact": {
                    "type": "string"
                },
                "device": {
                    "$ref": "#/definitions/dto.DeviceDto"
                },
                "otp": {
                    "description": "Must be numeric and exactly 6 digits long",
                    "type": "string"
                },
                "user_reference": {
                    "type": "string"
                }
            }
        },
        "dto.VerifyAccessTokenDTO": {
            "type": "object",
            "required": [
                "access_token"
            ],
            "properties": {
                "access_token": {
                    "description": "Access token should not be empty",
                    "type": "string"
                }
            }
        },
        "entity.Device": {
            "type": "object",
            "required": [
                "brand",
                "device_reference",
                "imei",
                "model"
            ],
            "properties": {
                "brand": {
                    "type": "string"
                },
                "device_reference": {
                    "type": "string"
                },
                "imei": {
                    "type": "string"
                },
                "model": {
                    "type": "string"
                },
                "type": {
                    "$ref": "#/definitions/shared.DeviceType"
                }
            }
        },
        "entity.Identity": {
            "type": "object",
            "required": [
                "created_on",
                "device",
                "identity_reference",
                "password_hash",
                "phone",
                "pin_hash",
                "updated_on",
                "user_reference"
            ],
            "properties": {
                "2fa_enabled": {
                    "type": "boolean"
                },
                "account_locked": {
                    "type": "boolean"
                },
                "created_on": {
                    "type": "string"
                },
                "device": {
                    "description": "Salt                string ` + "`" + `json:\"salt\" bson:\"salt\" validate:\"required\"` + "`" + `",
                    "allOf": [
                        {
                            "$ref": "#/definitions/entity.Device"
                        }
                    ]
                },
                "failed_login_attempts": {
                    "type": "integer",
                    "minimum": 0
                },
                "identity_reference": {
                    "type": "string"
                },
                "is_active": {
                    "type": "boolean"
                },
                "last_logged_in_at": {
                    "type": "string"
                },
                "password_hash": {
                    "type": "string"
                },
                "phone": {
                    "description": "Must be a valid E.164 format phone number",
                    "type": "string"
                },
                "pin_hash": {
                    "type": "string"
                },
                "updated_on": {
                    "type": "string"
                },
                "user_reference": {
                    "type": "string"
                }
            }
        },
        "helper.ErrorResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "error_reference": {
                    "type": "string"
                },
                "error_type": {
                    "type": "string"
                },
                "errors": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "timestamp": {
                    "type": "string"
                }
            }
        },
        "shared.DeviceType": {
            "type": "integer",
            "enum": [
                0,
                1,
                2
            ],
            "x-enum-varnames": [
                "Mobile",
                "Tablet",
                "Desktop"
            ]
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
